title: James Rowe's blog
description: > # this means to ignore newlines until "baseurl:"
  James (Jamie) Rowe's blog on molecular simulation, computational chemistry and biophysics.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jpkrowe.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: James (Jamie) Rowe # add your name
author-img: portrait.jpg # add your photo
about-author: I am a PhD student at Imperial College London interested in molecular simulation, computational chemistry and biophysics. # add description
social-twitter: j_rowe2000 # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: jpkrowe # add your Github handle
social-linkedin: james-rowe-74018425b # add your Linkedin handle
social-email: j.rowe22@imperial.ac.uk # add your Email address
social-bluesky: jrowe2000.bsky.social # add your Bluesky handle

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
